### ISSUE TITLE
Order.applyOrderTicketUp comparison issue

### ISSUE THREAD

**Issue by yortch** [quarkuscoffeeshop/quarkuscoffeeshop-counter#2]
@jeremyrdavis - I noticed these 2 lines are comparing the same variable...

```
        if(lineItem.getItemId().equals(lineItem.getItemId())){
```
Was this meant to compare to `ticketUp.getLineItemId()` instead?

https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-counter/blob/ca1590ebf452c2c5afcacc7649a96a31c2091684/src/main/java/io/quarkuscoffeeshop/counter/domain/Order.java#L65
https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-counter/blob/ca1590ebf452c2c5afcacc7649a96a31c2091684/src/main/java/io/quarkuscoffeeshop/counter/domain/Order.java#L72

**Comment by jeremyrdavis** [comment]
Fixed with 5.1.2
