### ISSUE TITLE
Order constructor issue

### ISSUE THREAD

**Issue by yortch** [quarkuscoffeeshop/quarkuscoffeeshop-counter#3]
Was this constructor meant to use the input `orderId` instead of generating a new one?

```
public Order(String orderId, OrderSource orderSource, Location location, String loyaltyMemberId, Instant timestamp, OrderStatus orderStatus, List<LineItem> baristaLineItems, List<LineItem> kitchenLineItems) {
```
https://github.com/quarkuscoffeeshop/quarkuscoffeeshop-counter/blob/ca1590ebf452c2c5afcacc7649a96a31c2091684/src/main/java/io/quarkuscoffeeshop/counter/domain/Order.java#L240

**Comment by jeremyrdavis** [comment]
Fixed with commit 5.1.3
